# Generated by Django 4.1.7 on 2023-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.TextField()),
                ("c_like", models.PositiveIntegerField(default="0", null=True)),
                ("c_dislike", models.PositiveIntegerField(default="0", null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
